name: "apps-test"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  TokenTest:
    runs-on:
      - "codebuild-createTokenTes-${{ github.run_id }}-${{ github.run_attempt }}"
      - "image:arm-lambda-nodejs20"
      - "instance-size:1GB"

    steps:
      - uses: kaito-tokyo/create-github-app-token-kms@main
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: 'awskms:{"region":"us-east-1",keyId:"alias/test3"}'
      
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: kaito-tokyo/create-github-app-token-kms